### ISSUE TITLE
Age range 54-59 inconsistent with others

### ISSUE THREAD

**Issue by Johannes-Schaefer** [Jiaxin-Pei/Potato-Prolific-Dataset#1]
According to the paper and raw_data csv files, the demographics regarding the age of the annotators contain the following ranges: 25-29, 30-34, 35-39, 40-44, 45-49, 50-54, 54-59, 60-64, >65.

If "54-59" is just a typo and the respective annotators were in fact in the range 55-59 (which would be consistent with the other ranges), this should be fixed.

**Comment by Jiaxin-Pei** [comment]
Hi @Johannes-Schaefer,

Thanks a lot for spotting this! Unfortunately, it seems that this issue came from the survey question in the original annotation task. We are so sorry for this issue. A potential solution is to merge the adjacent ranges and have 50-59, >60 to ensure the data is accurate.

**Comment by Johannes-Schaefer** [comment]
Thank you for the clarification.

I agree that merging the adjacent ranges is a reasonable solution.

To maintain the fine granularity of the age categories, we will work with the data as it is. This includes acknowledging the overlapping ranges in our application.
